services:
  web:
    build: .
    image: backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deneme_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asd123